version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nakormi

  nakormi:
    build: .
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dconfig.file=/workspace/application-prod.properties", "-jar", "nakormi.jar"]
    volumes:
      - './src/main/resources/application-prod.properties:/workspace/application-prod.properties'
    restart: always
    container_name: nakormi
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PG_DATASOURCE_URL=jdbc:postgresql://db:5432/nakormi
      - PG_NAME=pgadmin
      - PG_PASS=pgadmin
    tty: true
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=nakormi
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuramshin.py@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db


  # MinIO Console http://localhost:29001/
  minio:
    image: bitnami/minio
    container_name: minio
    ports:
      - "29000:9000"
      - "29001:9001"
    restart: always
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION_NAME: ru-mos
      MINIO_DEFAULT_BUCKETS: 'files,public:public'

volumes:
  postgres_data:
  pgadmin_data:
    driver: local
  minio_data:
    driver: local