name: CI/CD Pipeline for Nakormi Project

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew -Pvaadin.productionMode=true bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: build/libs

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: kuramshin-dev.ru
          username: ubuntu
          port: 50151
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/nakormi
            ./deploy.sh ${{ github.event.inputs.branch }}
